#!/bin/sh

# Copyright (c) 2013 Nicolas Legrand <nicolas.legrand@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

. doyoudatabnf.subr

DUMPSDIR="databnf-2012-11-15"
SETS="databnf_all_rdf_xml_2012-11-15.tar.gz databnf_externalrefs_xml_2012-11-15.tar.gz"
BACKEND="databnf"

cleandatabnfdumps $DUMPSDIR \
&& mkdirdatabnfdumps $DUMPSDIR \
&& getdatabnf $DUMPSDIR $SETS \
&& extractdatabnf $DUMPSDIR $SETS \
&& stopdatabnfbackend $BACKEND \
&& cleandatabnfbackend $BACKEND \
&& createdatabnfbackend $BACKEND \
&& startdatabnfbackend $BACKEND \
&& importdatabnf $DUMPSDIR \
&& cleandatabnfdumps $DUMPSDIR \
&& stopdatabnfbackend $BACKEND
